### PR TITLE
Remove script and callback / refactor / fix timeout default value

### PR DESCRIPTION
**Pull request by marcalexiei**
- Add `.editorconfig` (2 space feel free to change 😁 ).
- Replace `babel-preset-es2015` with `babel-env`.
- Add `Mocha` and removed `webpack` from `devDependencies`.
- Fix for #23.
- Refactor core js file.
- Minor Readme fixes.
- Fix some errors in `bower.json`.

@lamp Let me know if I can help with other changes!

### CODE REVIEW

**Comment by marcalexiei** [comment]
- Add `eslint` with `airbnb-base` configuration
- Call error wrapper function also for JSONP script `onerror` event (Fix #27)

**Comment by lamp** [comment]
Hi @marcalexiei Thanks for this, I'll take a look at it tonight and let's try and get this merged asap.

**Review by lamp — APPROVED** [review]
Looks really good to me, thank you so much for taking this on. I'll merge it in, test it against my test app and release it ASAP.

Thanks again, this is so much better.

**Comment by thetaiz** [comment]
Hi @lamp When will you be release this version?

**Comment by lamp** [comment]
@thetaiz Has been published now as `0.2.0`, sorry for the delay I forgot.

**Pull request merged**
